services:

    ollama:
        image: ollama/ollama
        volumes:
            - ollama-data:/root/.ollama
        ports:
            - "${OLLAMA_FORWARD_PORT:-11434}:${OLLAMA_PORT:-11434}"
        networks:
            - openllm-network

    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        volumes:
            - open-webui-data:/app/backend/data
        ports:
            - "${OPENOPENWEBUI_FORWARD_PORT:-3000}:${OPENWEBUI_PORT:-8080}"
        depends_on:
            - ollama
        networks:
            - openllm-network

volumes:

    ollama-data:
    open-webui-data:

networks:

    openllm-network:
        driver: bridge
